#Title: Car breakdown solution program
#Author: Daniel Mukenya Nyongesa
#License: MIT
#Date: 29/08/23
#Inspiration: Driving experience and car lover.
#Don't steal hahaha kidding, give me my credits. Love. In a bit

import sys


print("\t\t\t\t\t\t\t\tWELCOME TO FRADS CAR SOLUTIONS.")
print("\t\t\t\tVery warm welcome, we solve car problems before further actions.")
print("Kindly select the car model from the list below:")
print(f"1. Mobius\n"
      f"2. Toyota\n"
      f"3. Honda\n"
      f"4. Mazda\n"
      f"5. Subaru\n"
      f"6. Volkswagen\n"
      f"7. Mercedes\n"
      f"8. BMW\n"
      f"9. Exit\n")

choice = int(input("Which model: "))

def mobius():
      print(f"\t1.Quality control issues\n"
            f"\t2.Supply chain challenges\n"
            f"\t3.Rough road durability\n"
            f"\t4.Maintenance and servicing\n"
            f"\t5.Limited model range\n"
            f"\t6.Resale value\n"
            f"\t7.Perception & brand awareness\n"
            f"\t8.Financing & affordability\n"
            f"\t9.Regulatory & compliance issues\n"
            f"\t10.Competition\n")

def toyota():
      print(f"\t1.Brake problems\n"
            f"\t2.Suspension issues\n"
            f"\t3.Faulty water pumps\n"
            f"\t4.Fuel pump failures\n"
            f"\t5.Oil sludge in engines\n"
            f"\t6.Poor air conditioning\n")

def honda():
      print(f"\t1.Failing transmission\n"
            f"\t2.Engine issues\n"
            f"\t3.Defective airbags\n"
            f"\t4.Power steering Hose Failure\n"
            f"\t5.Car moves due to ignition interlock fault\n"
            f"\t6.Risk of automatic transmission locking up\n"
            f"\t7.Automatic transmission short circuiting\n"
            f"\t8.Fuel pump abrupt power loss\n")

def mazda():
      print(f"\t1.Clutch issues(Manual)\n"
            f"\t2.Untrustworthy engines\n"
            f"\t3.Brake booster issues\n"
            f"\t4.Melting Dashboards\n")

def subaru():
      print(f"\t1.Fuel pump failure\n"
            f"\t2.Oxygen sensor problems\n"
            f"\t3.Blown head gaskets\n"
            f"\t4.Oil leaks\n"
            f"\t5.Battery draining rapidly\n"
            f"\t6.Unintended acceleration\n"
            f"\t7.Crack windshields\n"
            f"\t8.Subaru starlink problems\n")

def volkswagen():
      print(f"\t1.Overactive check engine light\n"
            f"\t2.Oil problems\n"
            f"\t3.Coolant leaks\n"
            f"\t4.Vehicle overheating\n"
            f"\t5.Suspension issues\n")

def mercedes():
      print(f"\t1.Engine mounts failure\n"
            f"\t2.Engine misfires\n"
            f"\t3.Oil & Differential leaks\n"
            f"\t4.Air suspension failure\n"
            f"\t5.Transmission issues\n"
            f"\t6.Rusts easily & rapidly\n"
            f"\t7.Get ahead in the mercedes benz game\n")

def bmw():
      print(f"\t1.Oil leaks\n"
            f"\t2.Cooling system failure\n"
            f"\t3.Shaking steering wheel\n"
            f"\t4.Tail lamp problems\n")

if choice == 1:
      mobius()
      print(f"Want a guideline to fix each?\n"
            f"1. Yes\n"
            f"2. No\n")
      solulu = int(input("Choice: "))
      if solulu == 1:
            print(f"**** MOBIUS**** "
                  f"1. Quality control issuses - ")

      else:
            sys.exit()

if choice == 2:
      toyota()
      print(f"Want a guideline to fix each?\n"
            f"1. Yes\n"
            f"2. No\n")
      solulu = int(input("Choice: "))
      if solulu == 1:
            print(f"\t\t\t\t\t*** TOYOTA *** \n"
                  f"\t1. Brake problems :- \n\n"
                  f"Listen for unusual noises such as grinding, squeaking, or squealing when braking.\n"
                  f"Pay attention to any changes in braking performance, such as longer stopping distances or a soft brake pedal.\n"
                  f"Check for warning lights on the dashboard, like the ABS (Anti-lock Braking System) light\n"
                  f"Visually inspect the brake components, including brake pads, rotors, calipers, and brake lines.\n"
                  f"Look for signs of wear, damage, or corrosion.\n"
                  f"Check for any leaks around the brake lines and calipers.\n"
                  f"Check the brake fluid level in the master cylinder reservoir.\n"
                  f"Ensure that the brake fluid is clear and within the recommended level.\n"
                  f"If the fluid is dark or contaminated, it might need to be flushed and replaced.\n"
                  f"Measure the brake pad thickness. If the pads are worn beyond the recommended thickness, they need replacement.\n"
                  f"Inspect the brake rotors for uneven wear, scoring, or grooves. Resurfacing or replacement might be necessary.\n"
                  f"Check the calipers for proper operation. Ensure they are not sticking or causing uneven pressure on the brake pads.\n"
                  f"If a caliper is malfunctioning, it might need to be rebuilt or replaced.\n"
                  f"Examine the brake lines for any signs of leakage, corrosion, or damage.\n"
                  f"Leaking brake lines can result in loss of brake fluid and reduced braking efficiency.\n"
                  f"If the ABS light is on, use a diagnostic scanner to retrieve error codes from the ABS module.\n"
                  f"Address the specific issues indicated by the codes. This might involve repairing or replacing ABS sensors, modules, or related components.\n"
                  f"Clean the wheel speed sensors if they are covered in dirt or debris, as this can affect their performance.\n"
                  f"Check for damaged or malfunctioning sensors and replace them if needed.\n"
                  f"If you're unsure about diagnosing or fixing the issue yourself, it's recommended to take your Toyota to a certified mechanic or dealership.\n"
                  f"They have the expertise and specialized tools to diagnose and repair brake-related problems accurately.\n"
                  f"Follow the recommended brake maintenance schedule outlined in your Toyota's owner's manual.\n"
                  f"Regularly inspect and replace brake pads and rotors according to the manufacturer's guidelines.\n"
                  f"Use high-quality brake components that meet or exceed OEM specifications.\n\n"
                  f"\t2. Suspension issues:-\n\n"
                  f"Pay attention to any unusual noises while driving, such as clunking, rattling, or squeaking sounds.\n"
                  f"Observe changes in the vehicle's handling, such as excessive bouncing, drifting, or uneven tire wear.\n"
                  f"Check for uneven or abnormal tire wear patterns.\n"
                  f"Inspect the suspension components, including shock absorbers/struts, springs, control arms, bushings, and sway bar links.\n"
                  f"Look for signs of damage, corrosion, leaks, or wear on these components.\n"
                  f"Bounce each corner of the vehicle and observe how it responds. Excessive bouncing or a lack of rebound control may indicate worn shock absorbers or struts.\n"
                  f"Check for oil leaks around the shock absorber/strut body.\n"
                  f"Inspect the springs for signs of damage or sagging.\n"
                  f"Uneven ride height or a noticeably lower corner of the vehicle could indicate a broken or worn spring.\n"
                  f"Look for worn or damaged control arm bushings.\n"
                  f"Inspect control arms for signs of bending, rust, or other damage.\n"
                  f"Check for any play or looseness in the sway bar links.\n"
                  f"Worn or broken sway bar links can result in handling issues and noise.\n"
                  f"An incorrect wheel alignment can lead to uneven tire wear and handling problems. Have the alignment checked by a professional.\n"
                  f"If you're not confident in diagnosing or repairing suspension issues, take your Toyota to a certified mechanic or dealership.\n"
                  f"They can perform a comprehensive inspection, identify the specific problem, and recommend the appropriate repairs.\n"
                  f"Based on the diagnosis, replace any damaged or worn suspension components with high-quality parts that meet or exceed OEM specifications.\n"
                  f"Consider replacing components in pairs (e.g., both front struts) to maintain balanced suspension performance.\n"
                  f"Follow the manufacturer's recommended maintenance schedule for suspension components.\n"
                  f"Lubricate and inspect components like bushings and joints as needed.\n"
                  f"f you're interested in improving your Toyota's suspension performance, consider upgrading to aftermarket suspension components or kits.\n"
                  f"Make sure any modifications are compatible with your vehicle and driving needs.\n"
                  f"After repairs or replacements, take your Toyota for a test drive to ensure that the suspension issues are resolved.\n"
                  f"Pay attention to handling, ride comfort, and any remaining abnormal noises.\n\n"
                  f"\t3. Faulty water pumps:- \n\n"
                  f"Observe the engine temperature gauge. If it's consistently running hotter than normal, it could be due to a failing water pump.\n"
                  f"Listen for unusual noises coming from the front of the engine, such as a loud whining or grinding sound.\n"
                  f"Check for coolant leaks under the vehicle or around the water pump area.\n"
                  f"Allow the engine to cool down completely before working on it.\n"
                  f"Wear appropriate safety gear, such as gloves and safety glasses.\n"
                  f"Obtain a replacement water pump that matches your Toyota's make, model, and engine.\n"
                  f"Gather tools such as wrenches, sockets, pliers, a coolant drain pan, and a gasket scraper.\n"
                  f"Place a coolant drain pan under the radiator.\n"
                  f"Open the radiator drain plug to allow the coolant to drain into the pan.\n"
                  f"Loosen and remove the drive belts that are connected to the water pump.\n"
                  f"Disconnect the hoses and any electrical connections attached to the water pump.\n"
                  f"Remove the bolts securing the water pump to the engine.\n"
                  f"Use a gasket scraper to clean the mounting surface on the engine block where the water pump attaches.\n"
                  f"Place a new gasket on the new water pump or apply a thin layer of gasket sealant to the pump side of the gasket.\n"
                  f"Position the new water pump onto the engine block and secure it with the bolts.\n"
                  f"Reconnect the hoses and electrical connections that were disconnected earlier.\n"
                  f"Ensure all connections are secure.\n"
                  f"Put the drive belts back onto their pulleys and adjust their tension according to the manufacturer's specifications.\n"
                  f"Close the radiator drain plug.\n"
                  f"Refill the cooling system with the appropriate coolant mixture recommended for your Toyota.\n"
                  f"Bleed any air from the cooling system by using the designated bleed screws or valves.\n"
                  f"Start the engine and let it run while checking for coolant leaks around the water pump area.\n"
                  f"Observe the engine temperature gauge to ensure it's operating within the normal range.\n"
                  f"If the old coolant is still in good condition, you can save and reuse it. If not, dispose of it according to local regulations.\n\n"
                  f"\t4.Fuel pump Failures:- \n\n"
                  f"Observe symptoms like engine cranking but not starting, sputtering, loss of power, or engine stalling.\n"
                  f"Listen for a lack of humming noise from the fuel tank area when the ignition is turned to the ON position.\n"
                  f"Use a fuel pressure gauge to measure fuel pressure at the fuel rail; low or no pressure can indicate a failed fuel pump.\n"
                  f"Work in a well-ventilated area and away from open flames or sparks.\n"
                  f"Disconnect the vehicle's battery to prevent electrical accidents.\n"
                  f"Obtain a replacement fuel pump that matches your Toyota's make, model, and engine.\n"
                  f"Have tools such as wrenches, sockets, pliers, a jack and jack stands, and a container for fuel drainage.\n"
                  f"Loosen the fuel cap to release pressure from the fuel system.\n"
                  f"Alternatively, you can use the fuel pressure relief valve (if available) on the fuel rail.\n"
                  f"Disconnect the negative terminal of the vehicle's battery.\n"
                  f"Use a fuel line disconnect tool to disconnect the fuel lines from the fuel pump.\n"
                  f"Place a container under the disconnected lines to catch any spilled fuel.\n"
                  f"If the fuel pump is located inside the fuel tank (common for many vehicles), you'll need to access it by removing the tank.\n"
                  f"Raise the vehicle using a jack and secure it with jack stands.\n"
                  f"Remove the fuel tank by loosening and removing the retaining straps, and carefully lower it.\n"
                  f"Carefully disconnect the electrical connectors and hoses attached to the old fuel pump.\n"
                  f"Remove the fuel pump assembly from the tank.\n"
                  f"Install the new fuel pump assembly, ensuring all connections are secure.\n"
                  f"Reattach the fuel tank and secure it with the retaining straps.\n"
                  f"Reconnect the fuel lines and electrical connectors.\n"
                  f"Raise the vehicle and remove the jack stands.\n"
                  f"Reconnect the negative terminal of the battery.\n"
                  f"Refill the fuel tank with clean and fresh fuel.\n"
                  f"Turn the ignition key to the ON position for a few seconds to allow the fuel pump to prime the system before cranking the engine.\n"
                  f"Start the engine and let it run, checking for any unusual noises or signs of leaks.\n"
                  f"Test drive the vehicle to ensure proper fuel delivery and engine performance.\n\n"
                  f"\t5. Oil sludge in engines:-  \n\n"
                  f"Signs of oil sludge include poor engine performance, reduced fuel efficiency, engine knocking, and increased oil consumption.\n"
                  f"Drain the existing oil and replace it with fresh, high-quality engine oil. Also, replace the oil filter. Use the oil viscosity recommended in your Toyota's owner's manual.\n"
                  f"Some mechanics might recommend an engine flush to help remove the sludge.\n"
                  f" engine cleaning additives available that can help break down and dislodge sludge deposits.\n"
                  f"Consistently follow your Toyota's recommended oil change intervals using the appropriate oil type. Regular oil changes can prevent the buildup of sludge in the first place.\n"
                  f"The Positive Crankcase Ventilation (PCV) system is responsible for removing harmful gases from the engine. A malfunctioning PCV system can contribute to oil sludge buildup. Check and replace the PCV valve if necessary.\n"
                  f"The breather system allows the engine to release pressure. If this system is clogged or malfunctioning, it can lead to sludge formation. Make sure the breather system is clean and functioning properly.\n"
                  f"Overheating can accelerate sludge formation. Ensure your Toyota's cooling system is working correctly, and address any overheating issues promptly.\n"
                  f"Regular maintenance, including checking and replacing worn components, can prevent various engine issues, \n"
                  f"f the sludge buildup is severe, it's best to consult a professional mechanic. \n\n"
                  f"\t6.Poor air conditioning:-  \n\n"
                  f" Low refrigerant levels can result in reduced cooling efficiency. If the refrigerant is low, it could indicate a leak in the system\n"
                  f"AC system leaks can be a common cause of poor cooling performance. A professional mechanic can use specialized equipment to detect leaks and address them accordingly.\n"
                  f"The condenser is responsible for releasing heat from the refrigerant. If it's obstructed by debris or damaged, it can affect cooling performance. Inspect the condenser for any visible damage or obstructions.\n"
                  f"The AC compressor is the heart of the system. If it's not functioning properly, the AC won't cool effectively. Listen for any unusual noises coming from the compressor, and have it inspected by a professional if necessary."
                  f"The AC system relies on belts and pulleys to operate. Worn or damaged belts can impact the system's efficiency. Have the belts and pulleys checked during routine maintenance.\n"
                  f"A clogged or dirty cabin air filter can restrict airflow, leading to reduced cooling performance. Replace the cabin air filter according to your vehicle's recommended maintenance schedule.\n"
                  f"Make sure there are no obstructions blocking the vents both inside the cabin and in the engine compartment. Obstructed vents can restrict airflow, affecting cooling.\n"
                  f"The AC system relies on electrical components to function. If there's an issue with the electrical system, it can affect AC performance. A professional mechanic can diagnose and repair any electrical issues.\n"
                  f"The cooling fan helps dissipate heat from the AC system. If the cooling fan isn't working properly, it can lead to inadequate cooling. Check if the cooling fan is turning on as it should.\n"
                  f"If you're unable to identify the problem or if the issue is more complex, it's recommended to seek help from a qualified mechanic. \n\n"
                  f"\t\t\t****************Thank you. Toyota got you*************************\n\n")

      else:
            print("\t\tClosing the program.!!!!!")
            sys.exit()
if choice == 3:
      honda()
      print(f"Want a guideline to fix each?\n"
            f"1. Yes\n"
            f"2. No\n")
      solulu = int(input("Choice: "))
      if solulu == 1:
            print(f"\t\t\t\t\t*** HONDA *** \n"
                  f"1. Failing Transmissio \n\n"
                  f"")
if choice == 4:
      mazda()
if choice == 5:
      subaru()
      print(f"Want a guideline to fix each?\n"
            f"1. Yes\n"
            f"2. No\n")
      solulu = int(input("Choice: "))
      if solulu == 1:
            print(f"\t\t\t\t\t*** SUBARU *** \n"
                  f"\t1.Fuel pump failure:-  \n\n"
                  f"Before you start any work, ensure your safety and the safety of others. Park your vehicle in a safe, well-ventilated area, and disconnect the negative terminal of the battery to prevent electrical accidents.\n"
                  f" Identify common symptoms of a failing fuel pump, such as:\n"
                  f"\tEngine sputtering or stalling at high speeds or under heavy load.\n"
                  f"\tDifficulty starting the engine, especially when the fuel tank is low.\n"
                  f"\tA whining or buzzing noise coming from the fuel tank when the key is turned to the (ON) position (without starting the engine).\n"
                  f" To confirm that the fuel pump is the problem, you can perform a fuel pressure test. Here's how:\n"
                  f"\tLocate the fuel pressure test port on the fuel rail (it looks like a valve stem on a tire).\n"
                  f"\tAttach a fuel pressure gauge to the test port and follow the manufacturer's instructions for testing the pressure.\n"
                  f"\tTurn the key to the (ON) position (without starting the engine) to prime the fuel system. The pressure reading should match the manufacturer's specifications for your Subaru model.\n"
                  f"\tIf the pressure is significantly lower than the recommended value, it could indicate a failing fuel pump.\n"
                  f" Inspect the fuel pump relay and fuse. If they are faulty, it might not be the pump itself that's the problem. Replace any damaged or burnt-out relays or fuses.\n"
                  f"Use a multimeter to check if the fuel pump is receiving power when you turn the key to the (ON) position. If there's no power, it could be a wiring or electrical issue. Inspect the wiring and connectors for damage and repair as needed.\n"
                  f"With the key in the (ON) position, listen for a humming or buzzing noise from the fuel tank. This sound indicates that the fuel pump is functioning correctly. If you don't hear anything, it's a sign of a potential pump failure.\n"
                  f"Depending on your Subaru model, you may need to drop the fuel tank to access the fuel pump. This can be a complex and time-consuming task. Consult your vehicle's service manual or consider seeking professional help if you're not experienced with this procedure.\n"
                  f"If you've confirmed that the fuel pump is indeed the problem, you'll need to replace it. It's advisable to use an OEM (Original Equipment Manufacturer) fuel pump or a high-quality aftermarket equivalent.\n"
                  f"After replacing the fuel pump, reverse the steps to reassemble your Subaru, including reattaching the fuel lines, electrical connections, and securing the fuel tank.\n"
                  f"Once everything is back in place, start your Subaru and take it for a test drive to ensure the fuel pump is working correctly. Monitor for any abnormal symptoms.\n\n"
                  f"\t2.Oxygen sensor problems:- \n\n"
                  f"Common symptoms of a failing oxygen sensor include:\n"
                  f"\tDecreased fuel efficiency\n"
                  f"\tCheck Engine Light (CEL) or Malfunction Indicator Lamp (MIL) illuminated on the dashboard\n"
                  f"\tRough idling or engine misfires\n"
                  f"\tReduced engine performance\n"
                  f"\tIncreased exhaust emissions\n"
                  f"To pinpoint which oxygen sensor is causing the issue, you should retrieve the DTCs using an OBD-II scanner. Plug the scanner into the OBD-II port (usually located under the dashboard near the steering column), turn on the ignition (engine off), and read the stored fault codes.\n"
                  f"The DTCs will provide specific information about which oxygen sensor is problematic and may indicate the nature of the problem. Codes related to oxygen sensors often begin with (P013X) (upstream sensor) or (P014XP) (downstream sensor). For example, P0130 could indicate a problem with the upstream sensor.\n"
                  f"Before replacing the oxygen sensor, inspect the wiring and connectors associated with the sensor. Sometimes, loose or damaged wiring or poor connections can cause sensor-related issues. Repair or replace any damaged wires or connectors.\n"
                  f"If the DTC and inspection confirm that the oxygen sensor is faulty, you'll need to replace it. Here's how:\n"
                  f"\tLocate the problematic sensor. The upstream sensor is usually located in the exhaust manifold or pipe before the catalytic converter, while the downstream sensor is typically after the catalytic converter.\n"
                  f"\tDisconnect the electrical connector from the sensor.\n"
                  f"\tUse the appropriate O2 sensor socket and a breaker bar or ratchet to remove the sensor from its mounting location. It may require some force, but be careful not to damage the threads.\n"
                  f"\tApply anti-seize compound to the threads of the new oxygen sensor, then thread it into the same location where you removed the old one.\n"
                  f"\tReconnect the electrical connector.\n"
                  f"After replacing the sensor, clear the DTCs using the OBD-II scanner. This will reset the Check Engine Light.\n"
                  f"Take your Subaru for a test drive to ensure that the issue has been resolved. Monitor for any abnormal symptoms or the re-illumination of the Check Engine Light.\n"
                  f"Depending on your location and local emissions regulations, you may need to ensure that the vehicle's ECU (Engine Control Unit) is ready for emissions testing. Drive your Subaru according to the manufacturer's recommendations to reset the readiness monitors.\n\n"
                  f"\t3.Blown head gaskets:- \n\n"
                  f"Ensure your Subaru is parked in a safe, well-ventilated area, and disconnect the negative terminal of the battery to prevent electrical accidents.\n"
                  f"Open the radiator cap and the drain plug to remove the coolant. Catch the coolant in a container for proper disposal or recycling.\n"
                  f"Carefully remove components that are blocking access to the cylinder head, such as the air intake, throttle body, valve cover, and timing belt (if applicable). Disconnect any hoses and electrical connectors as necessary.\n"
                  f"Gradually loosen and remove the cylinder head bolts in the reverse order of the tightening sequence specified in your service manual. Keep track of the bolts' locations as they may have different lengths. If the head bolts are not reusable, you'll need to replace them.\n"
                  f"Carefully lift the cylinder head off the engine block. Be gentle to avoid damaging the mating surfaces.\n"
                  f"Use a gasket scraper and a rag to clean the mating surfaces of both the cylinder head and engine block. Ensure that there are no remnants of the old gasket or sealant.\n"
                  f"Place the new head gasket on the engine block, aligning it correctly. Pay attention to any directional markings on the gasket.\n"
                  f"Carefully lower the cylinder head onto the new head gasket. Make sure it's properly aligned with the dowel pins on the engine block.\n"
                  f"Follow the manufacturer's specified torque sequence and torque values to tighten the cylinder head bolts. This is crucial to ensure a proper seal. Gradually torque the bolts in multiple steps as specified in your service manual.\n"
                  f" Reattach all components that were removed, including the intake and exhaust manifold gaskets (replace these gaskets as well), hoses, electrical connectors, and timing belt (if applicable).\n"
                  f"Refill the coolant system with fresh coolant and ensure that the engine has the correct amount of oil.\n"
                  f"Start the engine and closely monitor for any coolant or oil leaks. Address any leaks immediately.\n"
                  f"Follow your vehicle's specific procedure for bleeding air from the cooling system to prevent overheating.\n"
                  f"Take your Subaru for a test drive and monitor the engine's performance and temperature. Keep an eye on the coolant level and temperature gauge.\n"
                  f"After a few hundred miles of driving, recheck the cylinder head bolt torque to ensure they haven't loosened.\n\n"
                  f"\t4.Oil leaks:- \n\n"
                  f"Start by visually inspecting the engine bay. Look for signs of oil accumulation, drips, or wet spots. Pay attention to areas around the valve covers, oil filter, oil pan, timing cover, and oil cooler (if equipped).\n"
                  f"Place a piece of cardboard or a clean sheet of paper under the vehicle overnight to help pinpoint the location of the oil leak. This will show you where the oil is dripping from.\n"
                  f"If the source of the leak isn't immediately obvious, you can add UV dye to the engine oil and use a UV light to trace the source of the leak more accurately.\n"
                  f"Assess how severe the oil leak is. A minor seepage may not require immediate attention, while a significant leak that results in rapid oil loss should be addressed promptly.\n"
                  f"Check if any oil filter, drain plug, or other components are loose. Sometimes, a simple tightening can solve the problem.\n"
                  f"If the leak is coming from gaskets or seals, such as the valve cover gaskets, oil pan gasket, or front/rear main seals, you'll need to replace the affected gasket or seal. This typically involves the following steps:\n"
                  f"\t Drain the engine oil.\n"
                  f"\tRemove the necessary components blocking access to the leaking gasket or seal.\n"
                  f"\tCarefully remove the old gasket or seal and clean the mating surfaces.\n"
                  f"\tInstall the new gasket or seal using proper torque specifications.\n"
                  f"\t Reassemble the components.\n"
                  f"\tRefill the engine with fresh oil.\n"
                  f"If the oil leak is near the oil filter, it might be due to a faulty oil filter or an improperly installed one. Check to ensure the oil filter is correctly installed and not damaged. Replace it if necessary.\n"
                  f"Inspect the oil pan and other engine components for damage, such as cracks or holes. If you find any, these parts may need to be repaired or replaced.\n"
                  f"After addressing the issue, monitor your Subaru for a few days to ensure the leak is no longer present. Check the oil level regularly to make sure you aren't losing oil excessively.\n"
                  f"If you are unable to locate or resolve the oil leak on your own, or if the leak persists after addressing visible issues, it's advisable to consult a professional mechanic. They can perform a more in-depth diagnosis and repair any complex issues.\n\n"
                  f"\t5.Battery draining rapidly:- \n\n"
                  f"This occurs when something in the vehicle is drawing power even when the engine is off. To check for this, you'll need a multimeter.\n"
                  f"Disconnect the negative (black) battery cable and set the multimeter to measure current (typically in the mA range).\n"
                  f"Connect the multimeter in series between the disconnected battery cable and the battery terminal. If there's a significant current draw (typically more than 50mA), there's a parasitic draw.\n"
                  f"Begin isolating circuits by removing fuses one at a time while monitoring the multimeter. When the current draw drops significantly, you've identified the circuit causing the problem.\n"
                  f"Ensure the battery terminals and cable connections are clean and tightly secured. Corroded or loose connections can lead to poor electrical contact and battery drain.\n"
                  f"A faulty alternator can lead to a drained battery. Have a mechanic check the alternator's output to ensure it's charging the battery correctly.\n"
                  f"If your battery is old or shows signs of weakness, it may not hold a charge properly. Have the battery tested at an auto parts store or by a mechanic to determine if it needs to be replaced.\n"
                  f"Certain components like a malfunctioning starter, ignition switch, or electrical accessories can contribute to battery drain. Have these components inspected and repaired or replaced if necessary.\n"
                  f"Ensure that all interior lights, including trunk and glovebox lights, turn off properly when not in use. Sometimes, a faulty switch or sensor can cause these lights to stay on.\n"
                  f"If your Subaru has aftermarket accessories like alarms, stereos, or GPS systems, they might be drawing power when the vehicle is off. Check if these are wired correctly and consider disconnecting them temporarily to see if it affects battery drain.\n"
                  f"In some cases, a software issue can cause a module in the vehicle to remain active, draining the battery. Ensure that your vehicle's software is up to date, and if the issue persists, consult with a dealership or mechanic for software-related solutions.\n"
                  f"Maintain your Subaru regularly, including keeping the battery terminals clean, changing the oil, and following the manufacturer's maintenance schedule. Well-maintained vehicles are less likely to have electrical issues.\n"
                  f"If you're unable to identify or resolve the issue on your own, it's best to take your Subaru to a qualified mechanic or dealership. They have the expertise and tools to diagnose and fix complex electrical problems.\n\n"
                  f"\t6.Unintended accelaration:- \n\n"
                  f"The most important thing is to stay calm and composed. Panic can make the situation worse.\n"
                  f"Immediately and firmly apply the brakes to slow down the vehicle. If you have a manual transmission, downshift to a lower gear to help reduce speed.\n"
                  f"If the brakes alone aren't sufficient to slow the vehicle down, shift the transmission into neutral. This will disengage the engine from the wheels and allow you to regain control of the vehicle.\n"
                  f"If shifting to neutral doesn't work or the vehicle continues to accelerate uncontrollably, try to turn off the engine. However, this should be a last resort, as it will also disable power steering and power brakes. Be cautious when turning off the engine and only do so if it's safe.\n"
                  f"Maintain control of the steering wheel to keep the vehicle in your lane and avoid obstacles. Be aware of your surroundings and try to navigate to a safe location, such as the shoulder of the road or an open parking lot.\n"
                  f"Activate your hazard lights to signal to other drivers that there is a problem with your vehicle.\n"
                  f"Once you have brought the vehicle to a stop safely, call for assistance. This could be a tow truck, a mechanic, or Subaru roadside assistance.\n"
                  f"After the incident, it's crucial to have your Subaru inspected by a qualified mechanic to identify and address the underlying issue that caused the unintended acceleration. It could be a mechanical or electronic issue, and fixing it is essential to prevent future occurrences.\n\n"
                  f"\t7.Crack windshields:- \n\n"
                  f"Start by examining the crack to determine its size, location, and severity. Note that smaller cracks can often be repaired, while larger or more extensive damage may require a windshield replacement.\n"
                  f"If the crack is smaller than a dollar bill (typically less than 6 inches in length) and not in the driver's line of sight, you may be able to repair it using a windshield repair kit available at auto parts stores. Follow the instructions on the kit carefully. These kits are designed to fill the crack with a resin that helps prevent it from spreading.\n"
                  f"For larger or more severe cracks, it's recommended to consult a professional auto glass repair or replacement service. They can assess the damage and determine if repair is possible or if a full windshield replacement is necessary.\n"
                  f"It's essential to address windshield damage promptly, as small cracks can worsen over time due to temperature changes, road vibrations, and other factors. Repairing the damage early can save you from having to replace the entire windshield.\n"
                  f"Check your auto insurance policy to see if windshield repair or replacement is covered. Many insurance policies offer coverage for this type of damage, and it may be a cost-effective way to address the issue.\n"
                  f"When seeking professional assistance, choose a reputable auto glass repair or replacement shop with experienced technicians. They will use high-quality materials and follow proper procedures to ensure your windshield is repaired or replaced correctly.\n"
                  f"If your windshield needs to be replaced, be prepared for the process. Ensure that the replacement windshield is of the same quality as the original and that the technician follows manufacturer specifications for installation.\n"
                  f"If you have a windshield repaired or replaced, follow the recommended curing time before driving the vehicle, as the adhesive used in the replacement process needs time to set and bond securely.\n"
                  f"After the repair or replacement, maintain your windshield by regularly cleaning it and inspecting for any new damage. This will help ensure its longevity and effectiveness in protecting you while driving.\n\n"
                  f"\t8.Subaru starlink problems:-  \n\n"
                  f"Ensure that your Subaru is properly connected to the internet. Many features of Subaru Starlink rely on an active internet connection. If you are using a mobile hotspot or a smartphone to provide internet access, make sure it is functioning correctly.\n"
                  f"Sometimes, a simple system restart can resolve minor issues. To do this, turn off the vehicle's ignition, wait a minute, and then start the vehicle again. This can help refresh the system.\n"
                  f"Outdated software can lead to compatibility issues and bugs. Check if there are any available updates for your Subaru's Starlink system. You can usually do this through the vehicle's settings menu or by visiting the Subaru website for software updates.\n"
                  f"If your Starlink system relies on a smartphone for connectivity, ensure that your phone has a stable data connection. Additionally, check if there are any issues with Bluetooth pairing between your phone and the car.\n"
                  f"As a last resort, you can reset the Starlink system to its factory defaults. This will erase all saved settings and data, so be sure to back up any important information before doing this. Consult your vehicle's owner's manual or contact Subaru customer support for instructions on how to perform a factory reset.\n"
                  f"If you've tried the above steps and are still experiencing issues, it's a good idea to contact Subaru customer support or visit a Subaru dealership. They can provide additional troubleshooting assistance and may be able to diagnose and resolve the problem more effectively.\n"
                  f"If the issue appears to be a hardware problem or a more complex software issue, it may require a visit to a Subaru service center. Certified Subaru technicians can diagnose and repair the system, ensuring it functions correctly.\n"
                  f"\t\t\t****************Thank you. Subaru got you*************************\n\n")
if choice == 6:
      volkswagen()
      print(f"Want a guideline to fix each?\n"
            f"1. Yes\n"
            f"2. No\n")
      solulu = int(input("Choice: "))
      if solulu == 1:
            print(f"\t\t\t\t\t*** VOLKSWAGEN  *** \n"
                  f"\t1.Overactive check engine light:- \n\n"
                  f"Make sure the gas cap is properly tightened. A loose gas cap can trigger the CEL.\n"
                  f"Inspect for any visible damage or disconnected wires in the engine bay.\n"
                  f"Obtain an OBD-II scanner. You can buy one or visit an auto parts store, which may offer free scanning services.\n"
                  f"Plug the scanner into the OBD-II port under the dashboard (usually near the steering column).\n"
                  f"Use the OBD-II scanner to read the error codes. These codes will provide specific information about the issue causing the CEL to illuminate. They will be in the format (PXXXX), where X represents numbers.\n"
                  f"Write down the error codes displayed on the scanner. This information is essential for diagnosing and addressing the problem.\n"
                  f"Check your Volkswagen's owner's manual to see if it provides any information about the specific error codes you've retrieved.\n"
                  f"Search online for the error codes and your specific Volkswagen model. Many automotive forums and websites offer information on common issues related to these codes.\n"
                  f"Depending on the error code and the problem it indicates, you may be able to address the issue yourself if you're familiar with automotive repairs. However, for complex problems, it's advisable to seek professional assistance from a qualified mechanic or dealership.\n"
                  f"After resolving the issue, you can clear the check engine light with your OBD-II scanner. This step isn't always necessary, as some codes may clear themselves after a few successful drive cycles. However, it can be helpful to verify that the problem is indeed fixed.\n"
                  f"To prevent future check engine light issues, adhere to your Volkswagen's recommended maintenance schedule, including oil changes, air filter replacements, and other routine service tasks.\n"
                  f"Keep an eye on the CEL after addressing the issue. If it comes back on, it may indicate a different problem or a related issue that wasn't completely resolved.\n\n"
                  f"\t2.Oil problems:- \n\n"
                  f"Park your Volkswagen on a level surface and turn off the engine.\n"
                  f"Wait a few minutes for the engine to cool down.\n"
                  f"Locate the oil dipstick, usually with a yellow handle, and pull it out.\n"
                  f"Wipe the dipstick clean and reinsert it fully.\n"
                  f"Pull the dipstick out again and check the oil level. It should be within the safe range on the dipstick. If it's low, add the appropriate type of oil until it reaches the correct level. Refer to your owner's manual for the recommended oil type.\n"
                  f"Look under your Volkswagen for any signs of oil leaks. Common areas for leaks include the oil pan, oil filter, valve cover gasket, and oil cooler.\n"
                  f"If you notice oil dripping or pooling, address the source of the leak immediately. Tighten loose bolts, replace gaskets, or fix damaged components as needed. If the issue persists, consult a mechanic.\n"
                  f"If your Volkswagen is consuming oil at an abnormal rate (often indicated by low oil levels between oil changes), it may be a sign of an internal engine problem. In this case, consult a professional mechanic to diagnose and repair the issue.\n"
                  f"If you notice warning lights on the dashboard related to oil pressure (e.g., oil pressure warning light), it's crucial to investigate the issue promptly. Low oil pressure can cause serious engine damage.\n"
                  f"Consult a mechanic to check the oil pressure using specialized equipment. Low oil pressure might indicate a failing oil pump, clogged oil passages, or other internal engine problems.\n"
                  f"Ensure you follow the manufacturer's recommended oil change schedule, which typically ranges from every 5,000 to 10,000 miles or as specified in your owner's manual.\n"
                  f"Use the correct oil type and filter specified by Volkswagen to ensure proper lubrication and engine performance.\n"
                  f"If you're unable to diagnose or fix the oil problem on your own, it's advisable to seek professional assistance from a certified Volkswagen mechanic or dealership. They have the expertise and equipment to accurately diagnose and repair complex issues.\n\n"
                  f"\t3.Coolant leaks:- \n\n"
                  f"Ensure your vehicle is parked on a level surface, the engine is cool, and you have safety gear like gloves and safety glasses.\n"
                  f"Inspect the ground beneath your vehicle for coolant puddles. This can give you a clue about the general area of the leak.\n"
                  f"Pop the hood and look for visible signs of coolant leaks around hoses, the radiator, water pump, thermostat housing, and other components in the cooling system.\n"
                  f"If you cannot locate the leak visually, consider using a cooling system pressure tester. This tool pressurizes the system without running the engine, making it easier to spot leaks. Look for any visible leaks or listen for hissing sounds.\n"
                  f"If you find loose or improperly secured hose clamps or connections, tighten them. Sometimes, a loose connection can lead to a coolant leak.\n"
                  f"Carefully examine all hoses for cracks, bulges, or signs of wear. Replace any damaged hoses.\n"
                  f"Check the radiator, water pump, thermostat housing, and other components for visible signs of leakage or corrosion. Replace any faulty parts.\n"
                  f"If the leak seems to be coming from a gasket, like the head gasket, intake manifold gasket, or thermostat housing gasket, these may need to be replaced. This is a more complex repair and may require professional assistance.\n"
                  f"Examine the radiator for visible damage, such as cracks or holes. If the radiator is damaged, it may need to be replaced.\n"
                  f"Check for coolant leaks inside the cabin. If you find coolant on the floor mats or a sweet smell in the cabin, the heater core could be leaking. This is another complex repair and should be done by a professional.\n"
                  f" Inspect the water pump for signs of leakage, such as a trail of dried coolant stains. If the water pump is leaking, it should be replaced.\n"
                  f" Once the leak is repaired, or the faulty component is replaced, flush the cooling system and refill it with the recommended coolant mixture according to your Volkswagen's specifications.\n"
                  f"After making the necessary repairs, start the engine and let it run while monitoring for any new leaks. Keep an eye on the temperature gauge to ensure the engine is running at the correct temperature.\n"
                  f"To prevent future coolant leaks, follow the manufacturer's recommended maintenance schedule, which includes periodic coolant system checks and replacement of hoses and components as they age.\n\n"
                  f"\t4.Vehicle overheating:- \n\n"
                  f"If your vehicle starts to overheat while driving, safely pull over to the side of the road or into a parking lot as soon as it is safe to do so.\n"
                  f"Turn off the engine and allow it to cool down. Do not attempt to open the radiator cap while the engine is hot, as hot coolant can cause burns.\n"
                  f"Once the engine has cooled down, open the hood and check the coolant level in the reservoir. Ensure it is at the proper level as indicated on the reservoir.\n"
                  f"Look for any signs of coolant leaks under the vehicle or around the engine bay. Leaks can lead to a loss of coolant and subsequent overheating.\n"
                  f"Start the engine and let it idle\n"
                  f"Observe the radiator fan. It should start running when the engine temperature rises. If the fan does not activate, it may be faulty, or there could be an issue with the fan relay or fuse.\n"
                  f"A faulty thermostat can prevent the coolant from circulating properly. If it's stuck closed, it can cause overheating. Consider replacing the thermostat if it's suspected to be faulty.\n"
                  f"A failing water pump can impede coolant circulation, leading to overheating. Look for signs of coolant leakage around the water pump, and if necessary, replace it.\n"
                  f"Inspect the radiator for damage or clogs. Debris or blockages can restrict airflow and cooling efficiency. Clean the radiator or replace it if needed\n"
                  f"Check coolant hoses and belts for signs of wear or damage. A collapsed hose or a broken belt can disrupt the cooling system's operation.\n"
                  f"Air pockets in the cooling system can hinder proper coolant circulation and lead to overheating. Follow the manufacturer's procedure for burping the cooling system to remove air.\n"
                  f"Overheating can also be caused by engine-related problems, such as a malfunctioning temperature sensor or a blown head gasket. If you suspect engine-related issues, it's best to have a professional mechanic diagnose and repair the problem.\n"
                  f"If you've addressed any issues found during your inspection, refill the cooling system with the appropriate coolant mixture according to your Volkswagen's specifications.\n"
                  f"Start the engine and let it run while monitoring the temperature gauge. Ensure that the temperature stays within the normal range.\n\n"
                  f"\t5.Suspension issues:- \n\n"
                  f"Start by visually inspecting the suspension components for any obvious signs of damage, such as bent or broken parts, leaking shocks or struts, or loose bolts. Common components include control arms, ball joints, bushings, struts, and shocks.\n"
                  f"Examine the condition of the tires. Uneven tire wear can indicate suspension problems. If you notice cupping, feathering, or other irregular wear patterns, this may be a sign of alignment or suspension issues.\n"
                  f"Ensure that your Volkswagen is at the correct ride height. A sagging suspension can affect handling and ride quality.\n"
                  f"Push down on each corner of the vehicle and release. The car should bounce back and come to a stop without excessive bouncing. If it continues to bounce, it could be a sign of worn shocks or struts.\n"
                  f"While the vehicle is stationary, gently turn the steering wheel from side to side. If there's excessive play or knocking sounds, it may indicate issues with the tie rods or steering components.\n"
                  f"Pay attention to any clunks, squeaks, or rattles while driving over bumps or during turns. These noises can help pinpoint the source of the suspension issue.\n"
                  f"If your Volkswagen tends to pull to one side or the steering wheel is off-center, it may indicate alignment issues. Have the wheel alignment checked and corrected if necessary.\n"
                  f"If you're unsure about the cause of the suspension problem or if it's a complex issue, it's advisable to take your Volkswagen to a qualified mechanic or a Volkswagen dealership for a comprehensive inspection.\n"
                  f"Depending on the diagnosis, you may need to replace various suspension components, such as:\n"
                  f"\tShocks and Struts: These are essential for ride comfort and stability. Worn shocks or struts should be replaced.\n"
                  f"\tControl Arms and Bushings: Damaged or worn control arms or bushings can lead to handling issues and noise. Replace them as needed.\n"
                  f"\tBall Joints: Worn ball joints can affect steering and suspension performance. Replace them if necessary.\n"
                  f"\tTie Rods and Sway Bar Links: These components can contribute to steering problems and uneven tire wear. Replace them if they're worn or damaged.\n"
                  f"Ensure your tires are balanced and rotated regularly. Proper tire maintenance can help prevent suspension issues and uneven tire wear.\n"
                  f"After making any necessary repairs or replacements, take your Volkswagen for a road test to ensure the suspension issues have been resolved. Pay attention to ride quality, handling, and noises.\n"
                  f"After making any necessary repairs or replacements, take your Volkswagen for a road test to ensure the suspension issues have been resolved. Pay attention to ride quality, handling, and noises.\n\n"
                  f"\t\t\t****************Thank you. Volkswagen got you*************************\n\n")

      else:
            print("\t\tClosing the program.!!!!!")
            sys.exit()

if choice == 7:
      mercedes()
      print(f"Want a guideline to fix each?\n"
            f"1. Yes\n"
            f"2. No\n")
      solulu = int(input("Choice: "))
      if solulu == 1:
            print(f"\t\t\t\t\t*** MERCEDES BENZ  *** \n"
                  f"\t1. Engine mounts failure:- \n\n"
                  f" Properly diagnose the issue to confirm that it's indeed an engine mount failure causing the problem. Symptoms of engine mount failure may include excessive engine movement, increased vibrations, unusual noises (clunks or thuds) during acceleration or braking, or even visible damage to the engine mounts themselves.\n"
                  f"Ensure you are working in a safe environment with proper tools and equipment. Safety glasses, gloves, and a sturdy jack or lift are essential.\n"
                  f"Different vehicles have various engine mounts, so you'll need to identify the specific mount that is causing the issue. In a Mercedes Benz, there are usually multiple engine mounts, including front, rear, and possibly side mounts.\n"
                  f"Once you've identified the faulty engine mount, you'll need to replace it. Here's a general procedure:\n"
                  f"\tDisconnect the Battery: This is a safety precaution to prevent accidental electrical issues while working on the engine.\n"
                  f"\t Lift the Vehicle: Use a jack or a lift to raise the vehicle and securely support it on jack stands. Ensure the vehicle is stable before proceeding.\n"
                  f"\tAccess the Mount: Depending on the location of the faulty mount, you may need to remove other components to access it. This could include parts of the exhaust system, undercarriage panels, or other parts blocking access.\n"
                  f"\tSupport the Engine: Use a suitable engine support bar to hold the engine in place. This prevents the engine from dropping when you remove the mount.\n"
                  f"\tRemove Old Mount: Use the appropriate tools to remove the bolts securing the old mount to the engine and chassis. This may involve using a socket wrench or other specialized tools.\n"
                  f"\tInstall New Mount: Place the new mount in position and hand-tighten the bolts. Make sure the mount is oriented correctly and fits snugly.\n"
                  f"\tTighten Bolts: Use a torque wrench to tighten the mounting bolts to the manufacturer's specifications. Overtightening or undertightening can lead to further issues.\n"
                  f"\t Reassemble: Reinstall any components that were removed to access the mount, such as exhaust parts or panels.\n"
                  f"\t Lower the Vehicle: Carefully lower the vehicle from the jack stands.\n"
                  f"\t Start the vehicle and observe for any unusual vibrations, noises, or issues. Take the car for a short test drive to ensure that the engine mount replacement has resolved the problem.\n"
                  f"Regular maintenance of your vehicle, including inspecting engine mounts during routine services, can help identify issues before they become severe.\n\n"
                  f"\t2. Engine Misfires:- \n\n"
                  f"If your Mercedes-Benz's check engine light is on, it often indicates that the engine control module (ECM) has detected a misfire. Use an OBD-II scanner to retrieve the specific error codes related to the misfire. These codes can provide valuable information about which cylinder is misfiring and potentially the underlying cause.\n"
                  f"Worn or fouled spark plugs are a common cause of misfires. Remove the spark plugs and inspect them for signs of wear, damage, or carbon buildup. If necessary, replace the spark plugs with new ones recommended by the manufacturer.\n"
                  f"Modern engines often have individual ignition coils for each cylinder. A faulty ignition coil can lead to misfires. You can diagnose this by swapping coils between cylinders and seeing if the misfire follows the coil. If it does, then the coil is likely the issue.\n"
                  f" Clogged or malfunctioning fuel injectors can cause uneven fuel delivery to the cylinders, resulting in misfires. You might need to clean or replace the fuel injectors as needed.\n"
                  f"Poor-quality or contaminated fuel can also lead to misfires. Ensure that you're using the recommended fuel type for your vehicle and that you're buying fuel from reputable sources.\n"
                  f" Low compression in a cylinder can cause misfires. A compression test can help identify if this is the issue. If the compression is significantly lower in a particular cylinder, it could indicate a problem with the piston rings, valves, or cylinder head gasket.\n"
                  f"Vacuum leaks can disrupt the air-fuel mixture and cause misfires. Carefully inspect the vacuum hoses and connections for any signs of damage or leaks.\n"
                  f"Vacuum leaks can disrupt the air-fuel mixture and cause misfires. Carefully inspect the vacuum hoses and connections for any signs of damage or leaks.\n"
                  f"If you're unsure about diagnosing and fixing the misfire yourself, it's best to take your Mercedes-Benz to a qualified mechanic or dealership. They have the expertise and specialized equipment to accurately diagnose and repair the issue.\n"
                  f"Preventive maintenance, such as regular oil changes, air filter replacements, and scheduled tune-ups, can help prevent misfires by keeping your engine in good condition.\n\n"
                  f"\t3. Oil & Differential leaks:- \n\n"
                  f"Clean the underside of the vehicle to remove any existing oil residue. This will make it easier to spot new leaks.\n"
                  f"Park the vehicle on a clean surface and allow it to run for a short period.\n"
                  f"Carefully inspect the areas where you suspect the leaks are originating from. Common places include the oil pan, valve cover gaskets, oil cooler, oil filter housing, and the differential.\n"
                  f"Look for signs of oil accumulation around gasket seams and seals.\n"
                  f"If you suspect a differential leak, check the differential housing and the axle seals. Differential leaks often result in oil accumulating around the rear axle area.\n"
                  f"Determine the severity of the leaks. Small seepages might not require immediate attention, but larger leaks should be addressed promptly to prevent damage to the engine or differential.\n"
                  f"Depending on the severity and location of the leaks, you might need to replace gaskets, seals, or other components.\n"
                  f"If the issue is related to gaskets or seals, replacing them with genuine Mercedes-Benz parts is recommended for optimal fit and performance.\n"
                  f"Some minor leaks can be addressed by experienced DIY enthusiasts, but for complex issues, it's recommended to seek professional help from authorized Mercedes-Benz service centers or qualified mechanics.\n"
                  f"Professional technicians have specialized tools and knowledge to diagnose and repair leaks accurately.\n"
                  f" Regularly scheduled maintenance, such as oil changes and fluid checks, can help prevent leaks by identifying and addressing issues early.\n"
                  f"Using high-quality engine oil and differential fluid recommended by Mercedes-Benz can help prevent leaks and maintain optimal performance.\n"
                  f"Be cautious when driving over rough terrain or obstacles that could damage the undercarriage and cause leaks.\n"
                  f"If you're unsure about diagnosing or fixing the leaks yourself, or if the leaks are extensive, it's best to consult a professional technician.\n\n"
                  f"\t4. Air suspension failure:- \n\n"
                  f"Many modern Mercedes-Benz vehicles with air suspension systems will display error messages or warnings on the dashboard if there's a suspension issue. Take note of any messages displayed.\n"
                  f"Inspect the vehicle for any signs of uneven suspension height, sagging, or abnormal gaps between the tires and the fenders. This can indicate a problem with the air suspension.\n"
                  f"Inspect the air suspension components, including air springs, air lines, valves, and the air compressor for visible damage or leaks.\n"
                  f"Ensure that all air lines and connections are secure and properly seated.\n"
                  f"The air compressor is responsible for inflating the air springs. Check the compressor for signs of damage and listen for unusual noises when the vehicle starts or the suspension is adjusted.\n"
                  f"If the compressor is not functioning properly, it may need to be replaced.\n"
                  f"Use a diagnostic scanner that's compatible with Mercedes-Benz vehicles to retrieve any fault codes from the air suspension system. These codes can provide insights into the specific issue.\n"
                  f"Air leaks are a common cause of air suspension failure. If you identify air leaks in the system, repair or replace the damaged components, which may include air springs, valves, or air lines.\n"
                  f"Modern air suspension systems use sensors to monitor and adjust the vehicle's ride height. Inspect the sensors for damage or misalignment.\n"
                  f"Check the leveling system to ensure it's working correctly.\n"
                  f"In some cases, resetting the air suspension system or performing a recalibration procedure might resolve issues related to incorrect ride height or sensor readings.\n"
                  f"Air suspension systems can be complex and require specialized equipment for diagnosis and repair. If you're not familiar with air suspension systems, it's recommended to seek professional help from a certified Mercedes-Benz technician or dealership.\n"
                  f"Depending on the severity of the issue, you might need to replace components such as air springs, sensors, or the air compressor.\n"
                  f"Regularly check and maintain your vehicle's air suspension system according to the manufacturer's recommendations to prevent future failures.\n\n"
                  f"\t5. Transmission issues:- \n\n"
                  f"Identify the symptoms of the transmission problem. These could include slipping, rough shifting, delayed engagement, unusual noises, or warning lights on the dashboard.\n"
                  f"Note when the issue occurs (e.g., during acceleration, shifting gears, at a certain speed) as this information can help with diagnosis.\n"
                  f"Low or degraded transmission fluid can cause shifting problems. Check the transmission fluid level and condition according to the manufacturer's instructions.\n"
                  f"Use a diagnostic scanner to retrieve any error codes stored in the vehicle's computer system. Transmission-related codes can provide valuable information about the issue.\n"
                  f"Modern transmissions are controlled by a complex network of sensors and solenoids. Ensure all electrical connections are secure and not damaged.\n"
                  f"Manual transmissions have linkages that connect the shifter to the transmission. Check for any loose or worn parts that could affect gear engagement.\n"
                  f"Sometimes, a reset of the TCM can resolve minor electronic glitches. This can often be done by disconnecting the vehicle's battery for a short period, but refer to the vehicle's manual for specific instructions.\n"
                  f"If the transmission fluid is dirty or burnt, performing a fluid and filter change might improve shifting performance. Consult the owner's manual for recommended service intervals.\n"
                  f"Many modern automatic transmissions adapt their shifting patterns to driving styles. Some issues might be resolved by performing a transmission adaptation procedure using diagnostic tools.\n"
                  f"If the issue is complex or if you're not experienced with transmission repairs, it's recommended to consult with a professional Mercedes-Benz technician or dealership.\n"
                  f"If the transmission has mechanical problems, such as worn clutches or damaged gears, it may need to be disassembled and repaired by experts.\n"
                  f"In severe cases, a transmission replacement might be necessary. Rebuilt or remanufactured transmissions from reputable sources can be options.\n"
                  f"Regularly scheduled maintenance, including checking transmission fluid, can help prevent issues and catch them early.\n\n"
                  f"\t6. Rusts easily & Rapidly\n\n"
                  f"Wash your Mercedes-Benz regularly, especially during the winter months or in areas with road salt. Salt and other chemicals used on roads can accelerate rust formation.\n"
                  f"Pay attention to the undercarriage, wheel wells, and other hidden areas where dirt and moisture can accumulate.\n"
                  f"Apply a high-quality wax or paint sealant to the vehicle's exterior. This provides a protective barrier against moisture and contaminants that can lead to rust.\n"
                  f"Park your vehicle in a dry, covered area whenever possible to protect it from rain, snow, and humidity.\n"
                  f"Touch up any scratches, chips, or dings in the paint as soon as you notice them. These areas are vulnerable to rust formation.\n"
                  f"There are rust prevention sprays and coatings available that can be applied to vulnerable areas like the undercarriage and inside the wheel wells.\n"
                  f"Regularly inspect your vehicle for signs of rust. Check hidden areas like the inside of the door frames, under carpets, and around the trunk or hood seams.\n"
                  f"If you notice any rust spots, address them promptly to prevent further spread.\n"
                  f"If you find rust, treat it as soon as possible. Sand down the affected area to remove the rust, apply a rust converter, and then repaint the area with matching paint.\n"
                  f"Some automotive service centers offer professional rust-proofing treatments. These treatments involve applying protective coatings to susceptible areas.\n"
                  f"Avoid using harsh chemicals or abrasive cleaning agents that could damage the vehicle's paint and protective coatings.\n"
                  f"When purchasing accessories or replacement parts, consider options made from rust-resistant materials like stainless steel or aluminum.\n"
                  f"If you live in an area with extreme rust conditions, consider purchasing a vehicle with rust-proofing features or moving to a rust-free location.\n\n"
                  f"\t7. Get ahead in the mercedes benz game\n\n"
                  f"Get a new benz my guy. Simple!!!!!\n"
                  f"\t\t\t****************Thank you. Mercedes got you*************************\n\n"
                  )
      else:
            print("\t\tClosing the program.!!!!!")
            sys.exit()

if choice == 8:
      bmw()
      print(f"Want a guideline to fix each?\n"
            f"1. Yes\n"
            f"2. No\n")
      solulu = int(input("Choice: "))
      if solulu == 1:
              print(f"\t\t\t\t\t*** BMW  *** \n"
                    f"\t1. Oil leaks:- \n\n"
                    f"Common areas for oil leaks in BMWs include the valve cover gasket, oil pan gasket, oil filter housing gasket, and various seals and hoses. Look for oil stains on the ground under your car or visible oil on the engine components.\n"
                    f"Once you've identified the source of the leak, you'll need to gather the necessary tools and replacement parts. The specific tools and parts required will depend on the location and severity of the leak. Common tools include wrenches, sockets, a torque wrench, and a jack and jack stands for lifting the car. You'll also need the appropriate gasket or seal for the repair.\n"
                    f"Always ensure your safety while working on your vehicle. Use safety glasses, gloves, and make sure the car is securely supported on jack stands.\n"
                    f" Before you can access and replace the leaking gasket or seal, you'll need to drain the engine oil from your BMW. Consult your vehicle's manual for the proper procedure.\n"
                    f"Depending on the location of the oil leak, you may need to remove various components such as the valve cover, oil pan, or oil filter housing. Be sure to follow the manufacturer's recommended procedures for disassembly.\n"
                    f"Inspect the gaskets and seals in the area of the leak. If they are damaged or worn, replace them with new ones. Apply a thin layer of engine oil or silicone gasket sealer to the gasket surfaces for a proper seal.\n"
                    f"Carefully reassemble the parts you removed, making sure to torque bolts to the manufacturer's specifications. Over-tightening can lead to new leaks or damage.\n"
                    f"Once everything is reassembled, refill the engine with the appropriate amount and type of engine oil specified in your owner's manual.\n"
                    f"Start the engine and let it run for a few minutes. Check for any oil leaks around the repaired area. If you still see leaks, you may need to readdress the repair.\n"
                    f"After fixing the leak, monitor your BMW's oil level regularly to ensure that it remains at the correct level.\n\n"
                    f"\t2.Cooling system failure:- \n\n"
                    f"Always ensure your safety when working on your vehicle. Allow the engine to cool down completely before opening the hood and working on the cooling system.\n"
                    f"Try to determine the nature of the cooling system problem. Common issues include overheating, coolant leaks, a malfunctioning thermostat, a faulty water pump, or a clogged radiator.\n"
                    f"Start by checking the coolant level in the expansion tank or reservoir. If it's low, top it up with the correct type of coolant recommended for your BMW. Be sure to use a coolant mixture that matches your climate.\n"
                    f"Look for any visible coolant leaks in the engine bay or under the car. Common areas for coolant leaks include the radiator, hoses, water pump, and connections. If you find a leak, replace the damaged component or tighten the connections as needed.\n"
                    f" Inspect the radiator for damage or corrosion. If it's damaged, you may need to replace it. Also, clean any debris or obstructions from the radiator's fins to ensure proper airflow.\n"
                    f"A faulty thermostat can cause overheating or inefficient cooling. To test it, remove it from the engine and place it in a pot of water on the stove. Heat the water, and the thermostat should open when it reaches its specified temperature (check your owner's manual for the thermostat's operating temperature). If it doesn't open, replace it.\n"
                    f" The water pump circulates coolant through the engine. If it fails, your engine can overheat. Inspect the water pump for leaks or unusual noises. If it's faulty, replace it.\n"
                    f"After making repairs or topping up the coolant, it's important to bleed the cooling system to remove any air pockets. Consult your vehicle's manual for the specific procedure, as it can vary by BMW model.\n"
                    f"If you can't identify the source of the issue, consider performing a pressure test on the cooling system. This test can help locate leaks that may not be immediately visible.\n"
                    f"After performing the necessary repairs and refilling the cooling system, monitor your BMW's temperature gauge while driving to ensure it remains within the normal range. If the engine still overheats, there may be a more complex issue that requires professional diagnosis.\n\n"
                    f"\t3.Shaking steering wheel\n\n"
                    f"Before you begin any diagnostic or repair work, ensure your safety by parking your BMW in a safe, flat area and engaging the parking brake.\n"
                    f"Irregular tire pressure can cause steering wheel vibrations. Use a tire pressure gauge to check that all your tires are inflated to the recommended pressure levels as specified in your vehicle's manual or on the door jamb sticker. Be sure to check the spare tire as well.\n"
                    f"Visually inspect your tires for any signs of damage, such as cuts, bulges, or uneven wear. If you notice any issues, it's advisable to replace the damaged tire(s) promptly.\n"
                    f"Unbalanced or improperly rotated tires can cause steering wheel vibrations. Take your BMW to a reputable tire shop or service center to have your tires balanced and rotated. They will use specialized equipment to ensure the weight distribution on each wheel is even.\n"
                    f"Misaligned wheels can also result in steering wheel vibrations. If you hit a pothole or curb recently, or if you notice uneven tire wear, it's a good idea to have your wheel alignment checked and corrected as necessary.\n"
                    f"Worn or damaged suspension components, such as control arms, bushings, or shocks, can lead to steering wheel vibrations. Inspect your suspension system for signs of damage or wear and replace any faulty components.\n"
                    f"Worn or warped brake rotors can cause steering wheel vibrations, especially when braking. If you feel the vibration mainly when applying the brakes, have your brake system inspected, and replace any damaged or worn components.\n"
                    f"Worn or damaged wheel bearings can also cause vibrations. If you hear unusual noises or experience vibrations that seem to come from the wheel area, have the wheel bearings inspected and replaced if necessary.\n"
                    f"Inspect the hubs and wheels for any visible damage or runout (wobbling). Damaged or bent wheels should be repaired or replaced.\n"
                    f"After addressing any of the above issues, take your BMW for a test drive to see if the steering wheel vibrations have been resolved. If the problem persists, consult with a qualified mechanic or BMW dealership, as there may be more complex issues with your vehicle's drivetrain or steering components that require professional diagnosis and repair.\n\n"
                    f"\t4.Tail lamp problems\n\n"
                    f"Start with the most common issue – burnt-out bulbs. Turn on your BMW's parking lights, headlights, and hazard lights, and have someone help you inspect all the tail lamps (including brake lights, turn signals, and running lights) to identify any bulbs that are not lit. Replace any burnt-out bulbs with the appropriate replacements. Refer to your owner's manual for the correct bulb types.\n"
                    f"If replacing the bulbs doesn't solve the issue, check the fuses that are associated with the tail lamps. Locate the fuse box in your BMW (often located in the glove compartment, under the dashboard, or in the trunk). Use the fuse diagram provided in your owner's manual or on the fuse box cover to identify the tail lamp fuse(s). If you find a blown fuse, replace it with one of the same amperage rating.\n"
                    f"Visually inspect the wiring and connectors leading to the tail lamps. Look for any signs of damage, loose connections, or corrosion. Damaged wires or loose connectors can cause electrical issues. Repair or replace any damaged wiring or connectors, and ensure all connections are secure.\n"
                    f"In some BMW models, the Light Control Module (LCM) controls various lighting functions, including the tail lamps. If you suspect a problem with the LCM, you may need to have it diagnosed and potentially replaced by a BMW dealership or qualified mechanic.\n"
                    f"Sometimes, the bulb holder or socket can become corroded or damaged, preventing the bulb from making a proper electrical connection. Inspect the bulb holders and sockets for any corrosion or damage. Clean or replace them as necessary.\n"
                    f" Ensure that the light switch on your BMW's dashboard is in the correct position and functioning properly. If it's faulty, replacing the switch may resolve the issue.\n"
                    f"Some modern BMWs have onboard diagnostic systems that can detect and store error codes related to lighting issues. You can use a diagnostic scanner to check for any stored error codes and get a better idea of the specific problem.\n"
                    f"If you've checked all the above components and still cannot resolve the tail lamp problem, or if you suspect an electrical issue beyond your expertise, it's advisable to consult a BMW dealership or an experienced BMW mechanic. They have the specialized tools and knowledge to diagnose and repair complex electrical problems.\n\n"
                    f"\t\t\t****************Thank you. BMW got you*************************\n\n")

      else:
            print("\t\tClosing the program.!!!!!")
            sys.exit()

if choice == 9:
      print("Exiting the program...........!!")
      sys.exit()



